DataDog/datadog-vale

styles/Datadog/headings.yml

Adds Datadog product names to the list of exceptions for sentence case in headers.
https://github.com/DataDog/documentation/pull/17997
---

✨Q2 Docs Hackathon✨ Headings Rule Update

---

styles/Datadog/pronouns.yml

Should fix false matches on our partials. Tested locally -  should be good to merge.
---

Fix false matches on pronouns

---

styles/Datadog/americanspelling.yml

Make a list for the `exceptions` section of the American Spelling rule which was alerting on https://github.com/DataDog/documentation/pull/18552.
DOCS-5702
---

American Spelling Rule Update

---

styles/Datadog/words.yml

Adds words and phrases to avoid with substitutions/suggested removals from Jorie's Words and Phrases to Avoid page in Docs4Docs.
Docs Style Council
---

Adds Words and Phrases to the Words Rule

---

styles/Datadog/words.yml

The `words.yml` warning is happening a lot, will discuss in the next Docs Style Council meeting.
#docs-style-council on Slack
---

Mute Error on Directions

---

styles/Datadog/sentencelength.yml

Sentence length makes more sense as a suggestion
---

Switch sentence length level to suggestion

---

styles/CWS-Descriptions/agent.yml
styles/CWS-Names/namecase.yml
styles/CWS-Names/namelength.yml
styles/CWS-Names/namenewvalue.yml
styles/CWS-Names/namestart.yml
styles/CWS-Names/nameweak.yml
styles/SIEM-Names/namecase.yml
styles/Vocab/Security/accept.txt

Add Vale styles used by the security products.
Centralizing Vale styles
---

Create security product styles

---

.github/CODEOWNERS

Add PDE team to CODEOWNERS file.
New security rule styles.
---

Add PDE team to CODEOWNERS

---

styles/SIEM-Names/namecase.yml

Update SIEM names with M365 Teams

---

styles/SIEM-Names/namecase.yml

github names

---

styles/SIEM-Names/namecase.yml

SIEM rule name for github detection

adding siem rule name

---

styles/SIEM-Names/namecase.yml

remove brackets

---

styles/SIEM-Names/namecase.yml

Add Sqreen for rule deprecation

---

styles/CWS-Names/namecase.yml

Create exceptions for rules that existed before the Vale check.
---

Add exceptions for existing CSM Threats rules

---

styles/SIEM-Names/namecase.yml

- adding exception for "Zendesk Automatic Redaction"

zendesk automatic redaction

---

styles/SIEM-Names/namecase.yml

auth0 rule

---

styles/SIEM-Names/namecase.yml

PAN rule name

---

styles/SIEM-Names/namecase.yml

Adding Jamf Protect to SIEM name cases

add Jamf Protect

---

styles/SIEM-Names/namecase.yml

slack rules

---

styles/SIEM-Names/namecase.yml

slack rule name

---

CONTRIBUTING.md

Fixes a minor typo in our contributing file.
The urge to correct typos.
---

Fix small typo in contributing.md

---

styles/CWS-Names/namecase.yml

Create an exception in the sentence case rule for `AWS CLI`
---

[CSM-T] Create AWS CLI exception

---

styles/config/vocabularies/AWS-services/accept.txt
styles/config/vocabularies/AWS-services/reject.txt

Add Fargate to the vocab for AWS services
---

Add Fargate

---

.github/workflows/yaml-linter.yml

Updates workflow permissions
---

Update workflow permissions

---

styles/Datadog/merge_conflict.yaml
styles/Datadog/merge_conflict.yml

Catch merge conflict annotations

---

styles/Datadog/words.yml

This PR stages the changes that will be published at `re:invent` to change the following:
NPM -> CNM
Network Performance Monitoring > Cloud Network Monitoring
This will create the rule so going forward we aren't manually updating the name with new changes.
I will merge on Dec. 2nd
Depends on: https://github.com/DataDog/documentation/pull/25101
---

[DOCS-9320] staging changes for NPM

---

styles/Datadog/headings.yml

Adds new products and features based on an internal source as of September 16, 2025 to `headings.yml` so that they can be ignored when not in sentence capitalization in a header.
Hackathon
You can check the ones I decided to add / leave off in this [sheet](https://docs.google.com/spreadsheets/d/12vEyRgL5bOkbWjVDVfRbJJfrI6Ix0C6wQU_EUnzxIaw/edit?gid=0#gid=0).
---

Add new products and features

---

styles/Datadog/words.yml

Added a few more words to the list of jargon [here](https://datadoghq.atlassian.net/wiki/spaces/WRITING/pages/5487427653/Jargon).
Writing team updated their list of jargon words.
---

Add more jargon to words list from writing team
